name: DockerImage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  container-build:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker compose up --build -d
      
    - name: Check status
      run: docker ps
      
    - name: View logs
      run: docker-compose logs
        

    - name: Stopping containers
      if: always()
      run: |
        docker compose down
